version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: master
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"